<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'56qX5biY55+l6K+G');
$cfg_Cs[2]=array(0,1,1,'5paw6Ze75Yqo5oCB');
$cfg_Cs[3]=array(0,1,1,'5YWz5LqO5oiR5Lus');
$cfg_Cs[4]=array(0,1,1,'6IGU57O75oiR5Lus');
$cfg_Cs[5]=array(0,1,1,'5qGI5L6L5bGV56S6');
$cfg_Cs[6]=array(0,1,1,'5Lqn5ZOB5Lit5b+D');
$cfg_Cs[7]=array(5,1,1,'5Y2n5a6k56qX5biY');
$cfg_Cs[8]=array(5,1,1,'5Yir5aKF56qX5biY');
$cfg_Cs[9]=array(6,1,1,'6YWS5bqX56qX5biY');
$cfg_Cs[10]=array(6,1,1,'5Yqe5YWs56qX5biY');
?>