<?php
$z[0]=Array("channel","\r\n      	<li><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></li>\r\n      	",100,343);
$z[0][4]['type']="top";
$z[0][4]['row']="10";
$z[0][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";
$z[1]=Array("flink","\r\n		 <li class=\"youqing\">[field:link /]</li>\r\n		",493,612);
$z[1][4]['row']="24";
$z[1][4]['type']="text";
$z[1][4]['titlelen']="24";
$z[1][4]['typeid']="0";

?>