<?php
$z[0]=Array("global","",128,160);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",370,402);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("channel","\r\n      	<li><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></li>\r\n      	",728,971);
$z[2][4]['type']="top";
$z[2][4]['row']="10";
$z[2][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";

?>