<?php
$z[0]=Array("global","",236,264);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("field","",277,296);
$z[1][4]['name']="title";
$z[2]=Array("global","",297,323);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","",364,393);
$z[3][4]['name']="keywords";
$z[4]=Array("field","",433,491);
$z[4][4]['name']="description";
$z[4][4]['function']="html2text(@me)";
$z[5]=Array("global","",509,541);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("include","",628,663);
$z[6][4]['filename']="head.htm";
$z[7]=Array("arclist","\r\n	<li class=\"wenzhang\">\r\n	<a href=\"[field:arcurl /]\" title=\"[field:title /]\">[field:title /]</a>\r\n	</li>\r\n	",976,1147);
$z[7][4]['titlelen']="42";
$z[7][4]['row']="8";
$z[7][4]['typeid']="1";
$z[8]=Array("global","",1449,1472);
$z[8][4]['name']="cfg_lxfs";
$z[9]=Array("field","",1874,1903);
$z[9][4]['name']="position";
$z[10]=Array("field","",1910,1932);
$z[10][4]['name']="typename";
$z[11]=Array("list","\r\n  <li><a href=\"[field:arcurl/]\">[field:title/]</a><span class=\"datetime\">[field:pubdate function=MyDate('Y-m-d',@me)/]</span></li>\r\n",2068,2239);
$z[11][4]['pagesize']="10";
$z[12]=Array("pagelist","",2290,2368);
$z[12][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[12][4]['listsize']="5";
$z[13]=Array("include","",2468,2505);
$z[13][4]['filename']="footer.htm";

?>