<?php
$z[0]=Array("global","",236,264);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("field","",277,296);
$z[1][4]['name']="title";
$z[2]=Array("global","",297,323);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","",364,393);
$z[3][4]['name']="keywords";
$z[4]=Array("field","",433,491);
$z[4][4]['name']="description";
$z[4][4]['function']="html2text(@me)";
$z[5]=Array("global","",509,541);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("include","",703,738);
$z[6][4]['filename']="head.htm";
$z[7]=Array("field","",989,1011);
$z[7][4]['name']="typename";
$z[8]=Array("channel","\r\n<h1 ><a href='[field:typeurl/]'>[field:typename/]</a></h1>\r\n",1058,1176);
$z[8][4]['type']="son";
$z[8][4]['currentstyle']="";
$z[9]=Array("global","",1449,1472);
$z[9][4]['name']="cfg_lxfs";
$z[10]=Array("field","",1763,1792);
$z[10][4]['name']="position";
$z[11]=Array("field","",1799,1821);
$z[11][4]['name']="typename";
$z[12]=Array("list","\r\n				<li>\r\n					<a title=\"[field:title/]\" href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\"/>\r\n					<p class=\"title\">[field:title/]</p></a>	</li>\r\n\r\n",1971,2158);
$z[12][4]['pagesize']="10";
$z[13]=Array("pagelist","",2222,2300);
$z[13][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[13][4]['listsize']="5";
$z[14]=Array("include","",2421,2458);
$z[14][4]['filename']="footer.htm";

?>